### PR TITLE
Meat Processing works now.

### PR DESCRIPTION
**Pull request by JBrooksCS**
# Description

Added Meat Processing functionality

## Type of change

Check all that apply.

- [ ] This pull request fixes a bug 
- [x ] This pull request adds a new feature
- [ ] This pull request will break existing functionality
- [x ] This change requires a documentation update

# Testing Instructions

Testing combo :   1 1 Enter 2 1 1 Enter 2 1 1 Enter 5 1 

# Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by carlybergthold — APPROVED** [review]
The end.

**Comment by carlybergthold** [comment]
> The end.

**Review by carlybergthold — DISMISSED** [review]
The.....real end?

**Review by carlybergthold — APPROVED** [review]
🚽 🍅

**Review by Preston-Jake — APPROVED** [review]
⚡️

**Pull request merged**
