### PR TITLE
can view animal count by type

### PR DESCRIPTION
**Pull request by carlybergthold**
# Description

When a user attempts to purchase an animal and place in a grazing field, they can see the number of total animals in that field as well as the count of each animal type.

## Type of change

Check all that apply.

- [ ] This pull request fixes a bug 
- [x] This pull request adds a new feature
- [ ] This pull request will break existing functionality
- [ ] This change requires a documentation update

# Testing Instructions

Try to create a grazing field and then purchase multiple animals - see if the field displays animals by type/count.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Preston-Jake — DISMISSED** [review]
👍

**Review by JBrooksCS — DISMISSED** [review]
Looks great!

**Review by C-Sandlin — APPROVED** [review]
🌮

**Review by JBrooksCS — APPROVED** [review]
I think this should be fine..

**Review by Preston-Jake — APPROVED** [review]
💯

**Pull request merged**
